language: go
os:
  - linux
arch:
  - amd64
go:
- '1.15'
services:
  - docker
before_script:
  - go mod download
script:
  - go test ./...
  - go build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then scripts/test/generic_unix.sh; fi
  # build all supported options with Gox (inside docker)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make build; fi
